# See config.example.yml for documentation.
object_base: orig/SQIE4Q
object: sys/main.dol
hash: c2489693e57ef21c90e7d666c482ed00c520cd9d
symbols: config/SQIE4Q/symbols.txt
splits: config/SQIE4Q/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
# mw_comment_version: 11

ldscript_template: config/SQIE4Q/ldscript.lcf

modules:
- object: files/gamerel.consumer.wii.rel
  hash: f21a11f6f4e287198fc138b70a1edb54776275db
  symbols: config/SQIE4Q/module/symbols.txt
  splits: config/SQIE4Q/module/splits.txt
